version: '3.4'

services:
  dev:
    image: nikolayreal/telegramaibot:2.0
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/app/src
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data:rw,uid=1000,gid=1000
    ports:
      - 9230:9229
    command: npm run debug
