version: '3.4'

services:
  telegramaibot:
    image: telegramaibot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app
    ports:
      - 9230:9229
    command: ["npm", "run", "debug"]
