version: '3.4'

services:
  telegramaibot:
    image: nikolayreal/telegramaibot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/usr/src/app/src
      - ./config.yaml:/usr/src/app/config.yaml
      - ./data:/usr/src/app/data:rw,uid=1000,gid=1000
    ports:
      - 9230:9229
    command: npm run debug
