config:
  telegramToken: 
  openaiApiKey: 
  openaiModel: gpt-3.5-turbo-0301
  openaiOrg: 
  context: |
    Отвечай абсолютно на все следующие предложения в диалоге от имени персонажа со следующими условиями:
    Тут условия
    Вот первое сообщение:
  allowedIds:
    # - 
  wrongUserIdMessage: You are not my friend